trigger:
- main  # Ensure this matches the branch name in your GitHub repository

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureSubscription: '92e0fdd0-53e0-473b-8050-3f49ec0d04ae'  # Your Azure subscription ID
  keyVaultName: 'nec-test'  # The name of your Azure Key Vault
  secretName: 'docker-password'  # The name of the secret in Azure Key Vault saving the Docker password

jobs:
- job: PrintSecret
  displayName: 'Fetch and Print Docker Password from Azure Key Vault'
  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Fetching Docker password from Azure Key Vault..."
        DOCKER_PASSWORD=$(az keyvault secret show --name $(secretName) --vault-name $(keyVaultName) --query value -o tsv)
        echo "Docker password retrieved successfully."
        echo "Docker Password: $DOCKER_PASSWORD"