trigger:
- main  # Ensure this matches the branch name in your GitHub repository

variables:
  azureSubscription: '92e0fdd0-53e0-473b-8050-3f49ec0d04ae'  # Your Azure subscription ID
  keyVaultName: 'nec-test'  # The name of your Azure Key Vault
  dockerRegistry: 'sandeep3414'  # Replace with your Docker registry name
  imageName: 'todo4'  # Replace with your Docker image name

jobs:
- job: BuildAndPush
  displayName: 'Build and Push Docker Image'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: $(azureSubscription)
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Fetching Docker password from Azure Key Vault..."
        DOCKER_PASSWORD=$(az keyvault secret show --name docker-password --vault-name $(keyVaultName) --query value -o tsv)
        echo "Docker password retrieved successfully."

        echo "Logging in to Docker..."
        echo $DOCKER_PASSWORD | docker login $(dockerRegistry) --username $(dockerRegistry) --password-stdin

  - script: |
      echo "Building Docker image..."
      docker build -t $(dockerRegistry)/$(imageName):$(Build.BuildId) .
    displayName: 'Build Docker Image'

  - script: |
      echo "Pushing Docker image to registry..."
      docker push $(dockerRegistry)/$(imageName):$(Build.BuildId)
    displayName: 'Push Docker Image'
